global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: besu
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 172.16.238.2:9545
          - 172.16.238.3:9545
          - 172.16.238.4:9545
          - 172.16.238.5:9545
          - 172.16.238.6:9545
          - 172.16.238.7:9545
          - 172.16.238.8:9545
          - 172.16.238.9:9545