global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: besu
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - validator-main-1:9545
          - validator-main-2:9545
          - validator-main-3:9545
          - validator-main-4:9545
          - validator-main-5:9545
          - validator-main-6:9545
          - fullnode-main-1:9545
          - fullnode-main-2:9545