version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prom.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      alien_network:

networks:
  alien_network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24