version: '2.1'
services:
  test-node-1:
    user: root
    container_name: test-node-1
    volumes:
      - ../node/besu-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data --genesis-file=genesis/genesis.json --bootnodes=enode://b22d383366d138424a82ceb47c0cbe47f9ec6acd101a3c65ddba91a78912ec8a535f2e533f9abf07cbcb49ea3172484d9d6693d5957ccbcc1b1f5ff4845ab107@172.20.0.2:30303 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all"
    ports:
      - "8546:8545"
      - "30304:30303"
    networks:
      test_network:
    restart: always

  test-node-2:
    user: root
    container_name: test-node-2
    volumes:
      - ../node/besu-2/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data --genesis-file=genesis/genesis.json --bootnodes=enode://b22d383366d138424a82ceb47c0cbe47f9ec6acd101a3c65ddba91a78912ec8a535f2e533f9abf07cbcb49ea3172484d9d6693d5957ccbcc1b1f5ff4845ab107@172.20.0.2:30303 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all"
    ports:
      - "8547:8545"
      - "30305:30303"
    networks:
      test_network:
    restart: always
    
  test-node-3:
    user: root
    container_name: test-node-3
    volumes:
      - ../node/besu-3/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data --genesis-file=genesis/genesis.json --bootnodes=enode://b22d383366d138424a82ceb47c0cbe47f9ec6acd101a3c65ddba91a78912ec8a535f2e533f9abf07cbcb49ea3172484d9d6693d5957ccbcc1b1f5ff4845ab107@172.20.0.2:30303 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all"
    ports:
      - "8548:8545"
      - "30306:30303"
    networks:
      test_network:
    restart: always

networks:
  test_network:
    external: true