version: '2.1'
services:
  alien-fullclient-node:
    user: root
    container_name: alien-fullclient-node
    volumes:
      - ../node/alien-0/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --genesis-file=genesis/genesis.json  --rpc-http-port=8551 --p2p-port=30309 --rpc-http-enabled --sync-mode=FULL --bootnodes=enode://c6de0814ad5ad50ffb06dacefba5362613ca49939a359b9b0d6f9426836d6dcc5b1d5468ee429d622118f66d5ee5293298ca3b2a5dcccbc641b28475eafb0932@172.18.0.2:30307 --data-path=data
    ports:
      - "8551:8551"
      - "30309:30309"
    networks:
      alien_network:
    restart: always

  alien-lightclient-node:
    user: root
    container_name: alien-lightclient-node
    volumes:
      - ../node/alien-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --genesis-file=genesis/genesis.json --rpc-http-port=8552 --p2p-port=30310 --rpc-http-enabled --sync-mode=FAST --bootnodes=enode://c6de0814ad5ad50ffb06dacefba5362613ca49939a359b9b0d6f9426836d6dcc5b1d5468ee429d622118f66d5ee5293298ca3b2a5dcccbc641b28475eafb0932@172.18.0.2:30307 --data-path=data
    ports:
      - "8552:8552"
      - "30310:30310"
    networks:
      alien_network:
    restart: always

networks:
  alien_network:
    external: true