version: '2.1'
services:
  alien-node-0:
    user: root
    container_name: alien-node-0
    volumes:
      - ../node/besu-0/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data  --rpc-http-port=8549 --p2p-port=30307 --genesis-file=genesis/genesis.json --min-gas-price=0 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all" --metrics-enabled --metrics-host=alien-node-0
    ports:
      - "8549:8549"
      - "30307:30307"
      - "9546:9546"
    networks:
      alien_network:
    restart: always

networks:
  alien_network:
    external: true