version: '2.1'
services:
  alien-fullclient-node:
    user: root
    container_name: alien-fullclient-node
    volumes:
      - ../node/alien-0/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --genesis-file=genesis/genesis.json  --rpc-http-port=8551 --p2p-port=30309 --rpc-http-enabled --sync-mode=FULL --bootnodes=enode://e5d55e8240bad5368f84aa0cb70a51a2c815c32e93994e682df63f51b66f5750e67a962ee87afb595124ded765947d0da8706d957e9ad590b40910ca668b4527@172.19.0.2:30307 --data-path=data
    ports:
      - "8551:8551"
      - "30309:30309"
    networks:
      alien_network:
    restart: always

  alien-lightclient-node:
    user: root
    container_name: alien-lightclient-node
    volumes:
      - ../node/alien-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --genesis-file=genesis/genesis.json --rpc-http-port=8552 --p2p-port=30310 --rpc-http-enabled --sync-mode=FAST --bootnodes=enode://e5d55e8240bad5368f84aa0cb70a51a2c815c32e93994e682df63f51b66f5750e67a962ee87afb595124ded765947d0da8706d957e9ad590b40910ca668b4527@172.19.0.2:30307 --data-path=data
    ports:
      - "8552:8552"
      - "30310:30310"
    networks:
      alien_network:
    restart: always

networks:
  alien_network:
    external: true