version: '2.1'
services:
  alien-fullclient-node:
    user: root
    container_name: alien-fullclient-node
    volumes:
      - ../node/alien-0/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --genesis-file=genesis/genesis.json  --rpc-http-port=8551 --p2p-port=30309 --rpc-http-enabled --sync-mode=FULL --bootnodes=enode://1994497ea3997938ec4f2ef9856ac240d6aa0cfc9b44a810efbd59347c2f27eb57fbd8d6c0c0027ad31adf2f467c2fda22211cfd277a571aaa587607091ce525@172.19.0.2:30307 --data-path=data
    ports:
      - "8551:8551"
      - "30309:30309"
    networks:
      clients_network:
    restart: always

  alien-lightclient-node:
    user: root
    container_name: alien-lightclient-node
    volumes:
      - ../node/alien-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - besu --genesis-file=genesis/genesis.json --rpc-http-port=8552 --p2p-port=30310 --rpc-http-enabled --sync-mode=FAST --bootnodes=enode://1994497ea3997938ec4f2ef9856ac240d6aa0cfc9b44a810efbd59347c2f27eb57fbd8d6c0c0027ad31adf2f467c2fda22211cfd277a571aaa587607091ce525@172.19.0.2:30307 --data-path=data
    ports:
      - "8552:8552"
      - "30310:30310"
    networks:
      clients_network:
    restart: always

networks:
  clients_network:
    external: true