version: '2.1'
services:
  alien-node-1:
    user: root
    container_name: alien-node-1
    volumes:
      - ../node/besu-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:latest
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data  --rpc-http-port=8550 --p2p-port=30308 --genesis-file=genesis/genesis.json --bootnodes=enode://c04074c099023be03a9860b4f238e577667e9b91d269afecca249ac4a2b788a23e424599737e0538166011b84bef2680dd5023d0457d27ca7e9bb3a091cf0b9a@172.19.0.2:30307 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all"
    ports:
      - "8550:8550"
      - "30308:30308"
    networks:
      alien_network:
    restart: always

networks:
  alien_network:
    external: true