services:
  redis:
    image: redis:7
    container_name: starfish-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      main_network:

  #starfish-firefly:
  #  image: alpine:latest
  #  container_name: starfish-firefly
  # networks:
  #    main_network:
  #      ipv4_address: 172.16.238.11
  #  entrypoint: /bin/sh -c "apk update && apk add --no-cache wget tar docker openssl bash && wget https://github.com/hyperledger/firefly-cli/releases/download/v1.3.2/firefly-cli_1.3.2_Linux_x86_64.tar.gz && tar -zxf firefly-cli_*.tar.gz -C /usr/local/bin ff && rm firefly-cli_*.tar.gz && ff init starfish-firefly 3 -p 8000 -v -n besu --chain-id 381660001 --remote-node-url http://172.16.238.2:8545 --remote-node-deploy --connector-config starfish/listrack/evmconnect.yaml && ff start starfish-firefly"

  # conector 1
  celery-beat-1:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-1-celery-beat
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/0
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8090
      REDIS_URL: redis://84.247.184.185:6379/0
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.tasks:celery",
        "beat",
        "--loglevel=info",
      ]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      main_network:

  celery-worker-1:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-1-celery-worker
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/0
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8090
      REDIS_URL: redis://84.247.184.185:6379/0
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.tasks:celery",
        "worker",
        "--loglevel=info",
      ]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      main_network:

  starfish-evm-connector-1:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-1
    ports:
      - "8080:80"
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/0
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8090
      REDIS_URL: redis://84.247.184.185:6379/0
      BLOCK_CONFIRMATIONS: "50"
    depends_on:
      redis:
        condition: service_healthy
      starfish-middleware-1:
        condition: service_started
    networks:
      main_network:
    restart: unless-stopped


  # conector 2
  celery-beat-2:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-2-celery-beat
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/1
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8091
      REDIS_URL: redis://84.247.184.185:6379/1
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.tasks:celery",
        "beat",
        "--loglevel=info",
      ]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      main_network:

  celery-worker-2:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-2-celery-worker
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/1
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8091
      REDIS_URL: redis://84.247.184.185:6379/1
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.tasks:celery",
        "worker",
        "--loglevel=info",
      ]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      main_network:

  starfish-evm-connector-2:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-2
    ports:
      - "8081:80"
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/1
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8091
      REDIS_URL: redis://84.247.184.185:6379/1
      BLOCK_CONFIRMATIONS: "50"
    depends_on:
      redis:
        condition: service_healthy
      starfish-middleware-2:
        condition: service_started
    networks:
      main_network:
    restart: unless-stopped


# conector 3
  celery-beat-3:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-3-celery-beat
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/2
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8092
      REDIS_URL: redis://84.247.184.185:6379/2
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.tasks:celery",
        "beat",
        "--loglevel=info",
      ]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      main_network:

  celery-worker-3:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-3-celery-worker
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/2
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8092
      REDIS_URL: redis://84.247.184.185:6379/2
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "app.tasks:celery",
        "worker",
        "--loglevel=info",
      ]
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      main_network:

  starfish-evm-connector-3:
    build: .
    image: starfish-evm-connector
    container_name: starfish-evm-connector-3
    ports:
      - "8082:80"
    environment:
      CELERY_BROKER_URL: redis://84.247.184.185:6379/2
      ETH_NODE_URL: "https://rpc-evm-sidechain.xrpl.org"
      MIDDLEWARE_BASE_URL: http://84.247.184.185:8092
      REDIS_URL: redis://84.247.184.185:6379/2
      BLOCK_CONFIRMATIONS: "50"
    depends_on:
      redis:
        condition: service_healthy
      starfish-middleware-3:
        condition: service_started
    networks:
      main_network:
    restart: unless-stopped

# middlewares 

  starfish-middleware-1:
    build: .
    image: starfish-middleware
    container_name: starfish-middleware-1
    volumes:
      - ../starfish/listrack/artifacts/contracts/LISTRACK_ETH.sol/LISTRACK_ETH.json:/app/artifacts/contracts/LISTRACK_ETH.json
    environment:
      CONNECTOR_EVM_API_BASE_URL: http://84.247.184.185:8080
      FIREFLY_API_HOST: "84.247.184.185"
      FIREFLY_API_PORT: 8000
      FIREFLY_API_SCHEME: "http"
      LISTRACK_CONTRACT_API_NAME: "listrack-eth"
      LISTRACK_CONTRACT_JSON_PATH: "/app/artifacts/contracts/LISTRACK_ETH.json"
      REDIS_URL: redis://84.247.184.185:6379/0
      MIDDLEWARE_CALLBACK_PORT: 8090
      MIDDLEWARE_CALLBACK_URL: http://84.247.184.185:8090
    networks:
      main_network:
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh", "-c", "./main.sh"]
    restart: unless-stopped

  starfish-middleware-2:
    build: .
    image: starfish-middleware
    container_name: starfish-middleware-2
    volumes:
      - ../starfish/listrack/artifacts/contracts/LISTRACK_ETH.sol/LISTRACK_ETH.json:/app/artifacts/contracts/LISTRACK_ETH.json
    environment:
      CONNECTOR_EVM_API_BASE_URL: http://84.247.184.185:8081
      FIREFLY_API_HOST: "84.247.184.185"
      FIREFLY_API_PORT: 8001
      FIREFLY_API_SCHEME: "http"
      LISTRACK_CONTRACT_API_NAME: "listrack-eth"
      LISTRACK_CONTRACT_JSON_PATH: "/app/artifacts/contracts/LISTRACK_ETH.json"
      REDIS_URL: redis://84.247.184.185:6379/1
      MIDDLEWARE_CALLBACK_PORT: 8091
      MIDDLEWARE_CALLBACK_URL: http://84.247.184.185:8091
    networks:
      main_network:
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh", "-c", "./main.sh"]
    restart: unless-stopped

  starfish-middleware-3:
    build: .
    image: starfish-middleware
    container_name: starfish-middleware-3
    volumes:
      - ../starfish/listrack/artifacts/contracts/LISTRACK_ETH.sol/LISTRACK_ETH.json:/app/artifacts/contracts/LISTRACK_ETH.json
    environment:
      CONNECTOR_EVM_API_BASE_URL: http://84.247.184.185:8082
      FIREFLY_API_HOST: "84.247.184.185"
      FIREFLY_API_PORT: 8002
      FIREFLY_API_SCHEME: "http"
      LISTRACK_CONTRACT_API_NAME: "listrack-eth"
      LISTRACK_CONTRACT_JSON_PATH: "/app/artifacts/contracts/LISTRACK_ETH.json"
      REDIS_URL: redis://84.247.184.185:6379/2
      MIDDLEWARE_CALLBACK_PORT: 8092
      MIDDLEWARE_CALLBACK_URL: http://84.247.184.185:8092
    networks:
      main_network:
    depends_on:
      redis:
        condition: service_healthy
    command: ["sh", "-c", "./main.sh"]
    restart: unless-stopped

networks:
  main_network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
