version: '2.1'
services:
  alien-node-1:
    user: root
    container_name: alien-node-1
    volumes:
      - ../node/besu-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.5.2-amd64
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data --genesis-file=genesis/genesis.json --bootnodes=<ENODE> --rpc-http-enabled --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-api=DEBUG,ETH,ADMIN,WEB3,QBFT,NET,PERM,TXPOOL,PLUGINS,MINER,TRACE --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9545
    ports:
      - "8550:8545"
      - "30308:30303"
    networks:
      alien_network:
        ipv4_address: 172.16.239.3
    restart: always

networks:
  alien_network:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24